### ISSUE TITLE
直播间屏蔽工具在界面下的屏蔽按钮消失不见

### ISSUE THREAD

**Issue by MingyueZheng** [jc3213/userscript#2]
只有管理列表，没有屏蔽按钮了，进入直播间后，屏蔽按钮也是没有显示；尝试过关闭其他的所有插件，均无效；
![{AF397374-8BB4-469F-BF56-91DE1D699B50}](https://github.com/user-attachments/assets/7cc81d50-2382-457f-9108-93f2e072702f)
以下是浏览器日志的日志；
[live.bilibili.com-1730608603912.log](https://github.com/user-attachments/files/17609388/live.bilibili.com-1730608603912.log)

**Comment by jc3213** [comment]
我好久没看直播了，所以没发现问题，回头我排查一下。

**Comment by jc3213** [comment]
[点此下载最新版本](https://jc3213.github.io/userscript/BilibiliLiveRoomFilter.user.js)

因为几乎重写了所有的东西，如果遇到问题请反馈，再就是[全部直播页面](https://live.bilibili.com/all)尚未支持。这已经用了我至少4个小时以上的时间了。

**Comment by MingyueZheng** [comment]
感谢佬的更新，希望佬一夜暴富(•̀ᴗ•́)و ̑̑
